server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qiuqiu?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.yszln.qiuqiu.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true